version: "3"

services:
  rollup:
    image: ${DOCKER_REGISTRY}jstz-rollup:${JSTZ_TAG}
    command: run
    restart: "no"
    env_file:
      - .env
    ports:
      - 8932:8932
    networks:
      - internal
    volumes:
      - logs:/root/logs

  node:
    image: ${DOCKER_REGISTRY}jstz-node:${JSTZ_TAG}
    # Modify the jstz-node to automatically create the kernel.log file if it beats the rollup to starting
    entrypoint: /bin/sh
    command: >
      -c "mkdir -p /roots/logs &&
          touch /roots/logs/kernel.log &&
          usr/bin/jstz-node run --rollup-endpoint http://rollup:8932 --kernel-log-path /root/logs/kernel.log --addr 0.0.0.0"
    restart: always
    ports:
      - 8933:8933
    networks:
      - internal
    volumes:
      - logs:/root/logs
    depends_on:
      - rollup

networks:
  internal:

volumes:
  logs:
