version: "3"

services:
  rollup:
    image: jstz-rollup:latest
    build:
      context: .
      dockerfile: crates/jstz_rollup/Dockerfile
      args:
        - OCTEZ_TAG
        - KERNEL_PATH
    command: run
    restart: "no"
    env_file:
      - .env
    ports:
      - 8932:8932
    networks:
      - internal
    volumes:
      - ./logs:/root/logs

  node:
    image: jstz-node:latest
    build:
      context: .
      dockerfile: crates/jstz_node/Dockerfile
    command: --rollup-endpoint http://rollup:8932 --kernel-log-path /root/logs/kernel.log --addr 0.0.0.0
    restart: always
    ports:
      - 8933:8933
    networks:
      - internal
    volumes:
      - ./logs:/root/logs
    depends_on:
      - rollup

networks:
  internal:
