name: Build CLI binary
inputs:
  platform:
    description: Platform that the binary can run on, e.g. linux, macos
    required: true
  arch:
    description: Architecture of CPU that the binary can run on, e.g. arm64, amd64
    required: true
  repo_token:
    description: API token that gives access to manage the target repo
    required: true
outputs:
  artefact_name:
    description: Name of the uploaded artefact
    value: ${{ steps.output.outputs.artefact_name }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - run: nix --version
      shell: bash
    - name: Format
      shell: bash
      run: nix --accept-flake-config fmt -- --fail-on-change
    - name: Prevent blst
      shell: bash
      run: nix --accept-flake-config develop -j auto --command sh -c '[ -z "$(cargo tree | grep blst)" ]'
    - name: Build
      shell: bash
      run: nix --accept-flake-config --log-format raw -L build -j auto .#jstz_cli
    - uses: actions/upload-artifact@v4
      with:
        name: jstz_${{ inputs.platform }}_${{ inputs.arch }}
        path: result/bin/jstz
    - name: Output
      id: output
      shell: bash
      run: echo "artefact_name=jstz_${{ inputs.platform }}_${{ inputs.arch }}" >> $GITHUB_OUTPUT
