[package]
name = "jstz_vitest"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
license-file.workspace = true
description.workspace = true
include = ["src"]

[dependencies]
anyhow.workspace = true
axum = { workspace = true, features = ["ws"] }
hyper.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
jstz_runtime = { path = "../jstz_runtime" }
deno_core.workspace = true
url.workspace = true
deno_error.workspace = true
node_resolver.workspace = true
deno_resolver.workspace = true
thiserror.workspace = true
sys_traits = { workspace = true, features = ["real"] }
deno_node.workspace = true
deno_fs.workspace = true
deno_permissions = { version = "0.49.0" }
deno_io = { version = "0.100.0" }
rustyline = { version = "=13.0.0",  features = ["custom-bindings"] }
libc = "0.2.168"
once_cell = "1.17.1"
deno_ast = { version = "=0.44.0", features = ["transpiling"] }

[target.'cfg(unix)'.dependencies]
nix = "=0.27.1"
deno_process = "0.5.0"
