[target.riscv64gc-unknown-linux-musl]
linker = "riscv64-unknown-linux-musl-g++"
rustflags = [
	"-C",
	"target-feature=+crt-static",
	"-C",
	"link-arg=-latomic",
	"-C",
	"link-arg=-lstdc++",
	"-C",
	"link-arg=-lsupc++",
	"-C",
	"link-arg=-lgcc",
	"-C",
	"link-arg=-lc"
]

