[profile.default]
slow-timeout = { period = "60s", terminate-after = 1 }

[[profile.default.overrides]]
filter = 'package(jstz_engine) and test(ui)'
slow-timeout = { period = "3m", terminate-after = 1 }
