name: Build RISCV kernel (reusable)

on:
  workflow_call:
    inputs:
      retention-days:
        description: "Number of days to retain the artifact"
        required: false
        type: number
        default: 1

jobs:
  build_riscv_kernel:
    name: Build RISCV kernel
    runs-on: [linux, nix]
    steps:
      - uses: actions/checkout@v4
      - name: Build kernel
        run: nix --accept-flake-config --log-format raw -L develop --command make riscv-pvm-kernel
      - uses: actions/upload-artifact@v4
        with:
          name: riscv_kernel
          path: target/riscv64gc-unknown-linux-musl/release/kernel-executable
          if-no-files-found: error
          retention-days: ${{ inputs.retention-days }}
