name: Continuous Integration

on:
  pull_request:
  merge_group:
  push:
    branches: [huanchengchang/jstz-400]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  build:
    name: Build
    runs-on: [x86_64, linux, nix]
    needs: [commitlint]
    steps:
      - uses: actions/checkout@v4
      - name: Run
        id: bench
        run: nix --accept-flake-config --log-format raw -L run .#tps_bench
