name: Continuous Integration

on:
  pull_request:
  merge_group:
  push:
    branches: [huanchengchang/jstz-941-3-test]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  build:
    name: Build
    uses: jstz-dev/jstz/.github/workflows/release.yml@huanchengchang/jstz-941-3-test
    with:
      octez_version: 23.3
      dry_run: true
      ref: huanchengchang/jstz-941-3-test
    secrets: inherit
