name: Continuous Integration

on:
  pull_request:
  merge_group:
  push:
    branches: [huanchengchang/jstz-931]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  set-input-values:
    name: Set input values for workflows triggered by tags
    runs-on: ubuntu-latest
    outputs:
      dry_run: ${{ steps.run.outputs.DRY_RUN }}
    steps:
      - id: run
        run: |
          dry_run=${{ inputs.dry_run }}
          # Default to false because workflows triggered by tags are not going to dry-run
          dry_run=${dry_run:-"true"}
          echo "DRY_RUN=${dry_run}" >> ${GITHUB_OUTPUT}
  linux-arm64:
    # Need to build in an alpine container to ship statically compiled binaries.
    # Target: aarch64-unknown-linux-musl
    name: Build CLI for Linux Arm64
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/huancheng-trili/cli_base:v1
      volumes:
        - /opt:/opt:rw,rshared
        - /opt:/__e/node20:ro,rshared
    steps:
      # Hack for github actions to work in arm64 alpine linux
      # https://github.com/actions/runner/issues/801#issuecomment-2976165281
      - name: Patch native Alpine NodeJS into Runner environment
        shell: sh
        run: |
          sed -i "/^ID=/s/alpine/NotpineForGHA/" /etc/os-release
          apk add nodejs --update-cache
          mkdir /opt/bin
          ln -s /usr/bin/node /opt/bin/node
      - uses: actions/checkout@v4
      - name: Build
        shell: sh
        run: make build-cli
      - uses: actions/upload-artifact@v4
        with:
          name: jstz_linux_arm64
          path: target/release/jstz
  test-linux-arm64:
    name: Test basic CLI usability for Linux Arm64
    runs-on: ubuntu-24.04-arm
    needs: [linux-arm64]
    steps:
      - uses: jstz-dev/jstz/.github/actions/test-cli@huanchengchang/jstz-931
        with:
          artefact_name: jstz_linux_arm64
  upload-github-release:
    name: Upload to github release
    runs-on: ubuntu-24.04
    needs: [test-linux-arm64, set-input-values]
    if: ${{ needs.set-input-values.outputs.dry_run == 'false' || needs.set-input-values.outputs.dry_run == false }}
    steps:
      - uses: actions/download-artifact@v5
        with:
          path: download
