name: Deploy dev docs

on:
  push:
    branches: [main]
  # In case the push build fails
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: dev-docs
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          DOC_URL=https://jstz-dev.github.io DOC_BASE_URL=/dev-docs/ npm run docs:build
          touch docs/build/.nojekyll
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_DEV_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_DEV_SECRET }}
          aws-region: eu-west-1
      - name: Upload to AWS
        run: aws s3 sync ./docs/build ${{ secrets.AWS_S3_DEV_PATH }} --delete
      - name: Invalidate AWS cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_DEV }} --paths '/*'
