name: Run benchmark job (reusable)

on:
  workflow_call:
    inputs:
      run-natively:
        description: "Run benchmark natively instead of using RISCV kernel"
        required: false
        type: boolean
        default: false
      benchmark-repeats:
        description: "Number of times to repeat each benchmark configuration"
        required: false
        type: number
        default: 5
      job-name:
        description: "Name for the benchmark job"
        required: false
        type: string
        default: "Benchmark RISCV kernel"

jobs:
  benchmark:
    name: ${{ inputs.job-name }}
    runs-on: benchmark
    steps:
      - uses: actions/checkout@v4
      - name: Download RISCV kernel
        if: ${{ !inputs.run-natively }}
        uses: actions/download-artifact@v5
        with:
          name: riscv_kernel
          path: riscv_kernel
      - name: Move kernel to bench directory
        if: ${{ !inputs.run-natively }}
        run: mv $GITHUB_WORKSPACE/riscv_kernel/kernel-executable crates/jstz_tps_bench
      - name: Run benchmark
        run: |
          cd crates/jstz_tps_bench
          if [ "${{ inputs.run-natively }}" = "true" ]; then
            nix --accept-flake-config --log-format raw -L develop --command sh -c 'export RUN_NATIVELY=1; ./run_all.sh ${{ inputs.benchmark-repeats }}'
          else
            nix --accept-flake-config --log-format raw -L develop --command sh -c 'export RISCV_KERNEL_PATH=./kernel-executable; ./run_all.sh ${{ inputs.benchmark-repeats }}'
          fi
          echo "### Benchmark summary" >> $GITHUB_STEP_SUMMARY
          cat ./results_all.log >> $GITHUB_STEP_SUMMARY
