name: Build npm package for jstz SDK

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Ref of the commit from which SDK will be build. Default to `main`
        required: false
        type: string
        default: main
      dry_run:
        description: Dry-run SDK build without publishing the built artefact
        type: boolean
        required: false
        default: true
  workflow_call:
    inputs:
      ref:
        description: Ref of the commit from which SDK will be build. Default to `main`
        required: false
        type: string
        default: main
      dry_run:
        description: Dry-run SDK build without publishing the built artefact
        type: boolean
        required: false
        default: true

jobs:
  build:
    name: Build SDK
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install wasm-pack
        shell: sh
        # The released install script https://drager.github.io/wasm-pack/installer/init.sh
        # is buggy at the time of implementation
        run: |
          export VERSION=0.13.1
          curl https://raw.githubusercontent.com/drager/wasm-pack/d881b07f63fc145f5af1eccb85e107cf7ea7e9c1/docs/_installer/init.sh -sSf | bash

          installed_version=$(wasm-pack -V)
          echo "Installed: $installed_version"
          if [[ $installed_version != *"$VERSION"* ]]; then
            echo "Installed version mismatch: expecting $VERSION"
            exit 1
          fi
      - name: Build
        shell: sh
        # Since the package is generated by wasm-pack, there might be some trivial defects in
        # package.json that lead to warnings. `pkg fix` corrects those things.
        run: |
          make build-sdk-wasm-pkg
          cd crates/jstz_sdk/pkg && npm pkg fix
      - name: Test install
        shell: bash
        run: |
          cd crates/jstz_sdk/pkg
          if [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
      - uses: actions/upload-artifact@v5
        with:
          name: jstz_sdk
          path: crates/jstz_sdk/pkg
          if-no-files-found: error
          retention-days: 1

  upload-github-release:
    name: Upload to GitHub release
    runs-on: ubuntu-24.04
    needs: [build]
    permissions:
      contents: write # Required for github release
    if: ${{ !inputs.dry_run }}
    steps:
      - uses: actions/download-artifact@v6
        with:
          path: jstz_sdk
      - name: Package
        shell: sh
        # zip the entire folder such that files are organised when the downloaded file is unzipped
        run: zip jstz_sdk.zip -r jstz_sdk
      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: jstz_sdk.zip
          tag_name: ${{ inputs.ref }}

  publish-to-npm:
    name: Publish to NPM
    runs-on: ubuntu-24.04
    needs: [build]
    permissions:
      id-token: write # Required for OIDC
    steps:
      - uses: actions/download-artifact@v6
        with:
          path: jstz_sdk
      - uses: jstz-dev/jstz/.github/actions/publish-npm-package@main
        with:
          package_dir: jstz_sdk
          dry_run: ${{ inputs.dry_run }}
