name: Build npm package for jstz SDK

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Ref of the commit from which SDK will be build. Default to `main`
        required: false
        type: string
        default: main
      dry_run:
        description: Dry-run SDK build without publishing the built artefact
        type: boolean
        required: false
        default: true
  workflow_call:
    inputs:
      ref:
        description: Ref of the commit from which SDK will be build. Default to `main`
        required: false
        type: string
        default: main
      dry_run:
        description: Dry-run SDK build without publishing the built artefact
        type: boolean
        required: false
        default: true

permissions:
  id-token: write # Required for OIDC
  contents: write # Required for github release

jobs:
  build:
    name: Build SDK
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install wasm-pack
        shell: sh
        run: |
          curl https://drager.github.io/wasm-pack/installer/init.sh -sSf | bash
      - name: Build
        shell: sh
        run: |
          make build-sdk-wasm-pkg
          # Since the package is generated by wasm-pack, there might be some trivial defects in
          # package.json that lead to warnings. `pkg fix` corrects those things.
          cd crates/jstz_sdk/pkg && npm pkg fix
      - name: Test install
        shell: bash
        run: |
          cd crates/jstz_sdk/pkg
          if [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: jstz_sdk
          path: crates/jstz_sdk/pkg
          if-no-files-found: error
          retention-days: 1

  upload-github-release:
    name: Upload to GitHub release
    runs-on: ubuntu-24.04
    needs: [build]
    if: ${{ !inputs.dry_run }}
    steps:
      - uses: actions/download-artifact@v5
        with:
          path: jstz_sdk
      - name: Package
        shell: sh
        # zip the entire folder such that files are organised when the downloaded file is unzipped
        run: zip jstz_sdk.zip -r jstz_sdk
      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: jstz_sdk.zip
          tag_name: ${{ inputs.ref }}

  publish-to-npm:
    name: Publish to NPM
    runs-on: ubuntu-24.04
    needs: [build]
    steps:
      - uses: actions/download-artifact@v5
        with:
          path: jstz_sdk
      - uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - name: Update npm # npm 11.5.1 or later is required for trusted publishing
        run: npm install -g npm@latest
      - name: Publish
        shell: bash
        run: |
          cd jstz_sdk
          if [[ "${{ inputs.dry_run }}" == "true" ]]; then
            echo "Dry-run npm publish"
            npm publish --provenance --access public --verbose --tag latest --dry-run
          else
            echo "Publish to NPM"
            npm publish --provenance --access public --verbose --tag latest
          fi
